### DISCUSSION TITLE
set the mode of charger in automation via add-on evcc☀️🚘- Solar Charging

### DISCUSSION THREAD

**Discussion by Marty56** [marq24/ha-evcc#10] [Q&A] [answered]
Hi,

I would like to set the mode of my charger in a script via the add-on "evcc☀️🚘- Solar Charging". 
What service can I use?
I have tried input_select service but was not successful.

**Comment by marq24** [comment]
IMHO `select.select_option`

**Comment by Marty56** [comment]
I tried
```
service: input_select.select_option
data:
  option: pv
target:
  entity_id: select.evcc_fahrradladegerat_mode
```

But it is not working

**Reply by marq24** [reply]
```
service: select.select_option
data:
  option: "pv"
target:
  entity_id: select.evcc_fahrradladegerat_mode
```

Options are 'off, pv, minpv, now'
