### DISCUSSION TITLE
What is the difference between the sensors "X" and "X [Tariff-API]"?

### DISCUSSION THREAD

**Discussion by mpw96** [marq24/ha-evcc#121] [Q&A] [answered]
Where X is either Grid Tariffs or Solar Prognoses.
Hi, could you please explain this for the rest of us? Looking at the code did not help me. Sorry.

I would like to build a nice forecast for sun and price with APEX Chart Card (something like this https://www.youtube.com/watch?v=R0knPiJk3ts) and I want to pull all data from evcc.

T&R
MP

**Comment by mpw96** [comment]
![Screenshot 2025-04-15 at 18 11 15](https://github.com/user-attachments/assets/c9531c83-5831-425b-b48b-a99ce87ebe0c)

On the shoulders of giants! Thank you @marq24!

**Comment by mpw96** [comment]
```

type: custom:apexcharts-card
apex_config:
  chart:
    height: 400px
  colorize_states: true
graph_span: 2d
span:
  start: day
  offset: "+0"
now:
  show: true
  label: Jetzt
yaxis:
  - id: kwh
    min: 0
    apex_config:
      tickAmount: 5
  - id: euro
    min: 0
    max: 1.5
    opposite: true
    decimals: 4
    apex_config:
      tickAmount: 5
series:
  - entity: sensor.evcc_tariff_api_solar
    unit: kWh
    yaxis_id: kwh
    name: Prognose
    type: line
    color: yellow
    data_generator: |
      return entity.attributes.rates.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.rates[index]["value"]/1000.0]
      });
    show:
      legend_value: false
      in_header: false
    stroke_width: 4
    float_precision: 2
    extend_to: false
  - entity: sensor.evcc_pv_power
    unit: kWh
    transform: return x/1000.0
    yaxis_id: kwh
    name: Ertrag
    type: area
    color: green
    show:
      legend_value: false
      in_header: false
    stroke_width: 2
    float_precision: 2
    extend_to: false
    group_by:
      func: avg
  - entity: sensor.evcc_tariff_api_grid
    unit: Euro
    yaxis_id: euro
    name: Preis
    type: column
    color: orange
    data_generator: |
      return entity.attributes.rates.map((start1, index1) => {
        return [new Date(start1["start"]).getTime(), entity.attributes.rates[index1]["value"]]
      });
    show:
      legend_value: false
      in_header: false
    stroke_width: 1
    float_precision: 4
```
