### DISCUSSION TITLE
Vehicle Configuration with Custom Sensor Support HTTP

### DISCUSSION THREAD

**Discussion by Brambuu** [marq24/ha-evcc#138] [Q&A]
Hi everyone! 
I am trying to create a new vehicle in EVCC with the use of the sensors which I received from another sensor. 
From looking at the example provided at "HA_AS_EVCC_SOURCE.md" I could fill in like 50% of it. 

However, since my HTTP knowledge is very lacking, I was wondering how I can get the remaining ones filled in (maxcurrent, wakeup, status, climater). I can not use the GET method for that, but something else. I guess. 

Could anyone support me with this? All sensors are comming from https://github.com/andreadegiovine/homeassistant-stellantis-vehicles

```
vehicles:
  - name: Peugeot208T
    type: custom
    title: Peugeot208T # display name for UI
    capacity: 50 # battery capacity (kWh)
    soc: # battery soc (%)
      source: http
      uri: http://[YOUR-HA-INSTANCE]:8123/api/states/sensor.VIN_battery
      method: GET
      headers:
        - Authorization: Bearer [YOUR-TOKEN-HERE]
      insecure: true
      jq: .state|tonumber
      timeout: 2s
    status: # optional charge status (A..F)
      source: # plugin type
      # ...
    range: # optional electric range (km)
      source: http
      uri: http://[YOUR-HA-INSTANCE]:8123/api/states/sensor.VIN_range
      method: GET
      headers:
        - Authorization: Bearer [YOUR-TOKEN-HERE]
      insecure: true
      jq: .state|tonumber
      timeout: 2s
    odometer: # optional odometer (km)
      source: http
      uri: http://[YOUR-HA-INSTANCE]:8123/api/states/sensor.VIN_milleage
      method: GET
      headers:
        - Authorization: Bearer [YOUR-TOKEN-HERE]
      insecure: true
      jq: .state|tonumber
      timeout: 2s
    climater: # optional climate status (true/false)
      source: # plugin type
      # ...
    wakeup: # optional vehicle wake up command
      source: # plugin type
      # ...
    maxcurrent: # set charger max current (A)
      source: # plugin type
      # ...
```

**Comment by marq24** [comment]
... IMHO: no need to provide 'odometer', 'climater', 'wakeup' or 'maxcurrent'...

for 'status' you must create a own ha template entry where you return the state: A, B or C based on the evcc documentation... 

return A when DISCONNECTED
return B when somehow CONNECTED
return C when somehow CHARGING

**Reply by Brambuu** [reply]
Isn't the wakeup command used to get new data? I thought that's quite useful. Especially with Stellantis who is not that great in keeping all data up to date.

**Reply by marq24** [reply]
well - for evcc this is optional...

**Comment by marq24** [comment]
I just found some additional (detailed) info how to deal with the status:

### Additional Template Sensor is need to provide EVCC vehicle status

We need to create a HA sensor that will provide the status of charging - this will be A, B, C, D, E, F as described in the [evcc documentation](https://github.com/evcc-io/evcc/blob/master/api/chargemodestatus.go).

| Status | Code | Fzg. angeschlossen | Laden aktiv | Description                                                                |
| --- |------|--------------------|-------------|----------------------------------------------------------------------------|
| StatusA | "A"  | nein               | nein        | Ladestation betriebsbereit, Fahrzeug getrennt                              |
| StatusB | "B"  | ja                 | nein        | Fahrzeug verbunden, Netzspannung liegt nicht an                            |
| StatusC | "C"  | ja                 | ja          | Fahrzeug lädt, Netzspannung liegt an                                       |
| StatusD | "D"  | ja                 | ja          | Fahrzeug lädt mit externer Belüfungsanforderung (für Blei-Säure-Batterien) |
| StatusE | "E"  | ja                 | nein        | Fehler Fahrzeug / Kabel (CP-Kurzschluss, 0V)                               |
| StatusF | "F"  | ja                 | nein        | Fehler EVSE oder Abstecken simulieren (CP-Wake-up, -12V)                   |

The original evcc code can be found [here](https://github.com/evcc-io/evcc/blob/c338a8ec0cbf1df853e300bf50a213fae2b9ff69/vehicle/ford/provider.go#L58C5-L76). Here is the section just for your reference:

```go
// Status implements the api.ChargeState interface
func (v *Provider) Status() (api.ChargeStatus, error) {
    status := api.StatusNone

    res, err := v.statusG()
    if err == nil {
        switch res.Metrics.XevPlugChargerStatus.Value {
        case "DISCONNECTED":
            status = api.StatusA // disconnected
        case "CONNECTED":
            status = api.StatusB // connected, not charging
        case "CHARGING", "CHARGINGAC":
            status = api.StatusC // charging
        default:
            err = fmt.Errorf("unknown charge status: %s", res.Metrics.XevPlugChargerStatus.Value)
        }
    }

    return status, err
}
```

From the original Ford evcc integration it looks like that we only needs to provide status A, B or C and we can get this from the HA sensor status from `sensor.fordpass_[YOUR-VIN-HERE]_elvehcharging` (you need to adjust the following template sensor if you have a different sensor name).

#### Create the template sensor
1. Go to the HA configuration and select `Configuration` -> `Helpers` -> `Add Helper`
2. Select `Template` and in the next selection select `Template for Sensor`
3. Enter a name for the sensor (e.g. `fordpass_[YOUR-VIN-HERE]_evcc_charging_code`)
4. Enter the following template code:
   ```
   {% set val = states('sensor.fordpass_[YOUR-VIN-HERE]_elvehcharging')|upper %}{% if val == 'DISCONNECTED' -%}A{% elif val == 'CONNECTED' -%}B{% elif val == 'CHARGING' or val == 'CHARGINGAC' -%}C{%- else %}UNKNOWN{%- endif %}
   ```
5. Optional you can select your fordpass Vehicle as `Device`
6. Click `OK`

As alternative, you can add the following code to your template section of the `configuration.yaml`:

```yaml
  - unique_id: template.uid_fordpass_[YOUR-VIN-HERE]_evcc_code
    sensor:
      - name: 'fordpass [YOUR-VIN-HERE] EVCC Charging code'
        unique_id: 'uid_fordpass_[YOUR-VIN-HERE]_evcc_charging_code'
        icon: mdi:state-machine
        state: >
           {% set val = states('sensor.fordpass_[YOUR-VIN-HERE]_elvehcharging')|upper %}{% if val == 'DISCONNECTED' -%}A{% elif val == 'CONNECTED' -%}B{% elif val == 'CHARGING' or val == 'CHARGINGAC' -%}C{%- else %}UNKNOWN{%- endif %}
```

### Check if the status of the new template sensor is working

Make sure that the new created sensor `sensor.fordpass_[YOUR-VIN-HERE]_evcc_charging_code` will provide the correct status code (A, B or C) - you can check this in the HA Developer Tools -> States.
