### ISSUE TITLE
Can we have the maxPower parameter (Load Management) available?

### ISSUE THREAD

**Issue by RikMe** [marq24/ha-evcc#59]
### Description

Would be great to be able to dynamically set the maxPower parameter for load management. 

Potential use case: "Capaciteitstarief" in Belgium.

**Comment by marq24** [comment]
What's about the `number.evcc_[LOADPOINT]_limit_energy` entity? You can set this to any kWh (or remove it by setting this value to 0) - if this is not the evcc parameter you want to adjust - please be so kind and provide a screenshot of evcc showing the "setting"... TIA

**Comment by RikMe** [comment]
Hi, thanks for following up!

Thats not the paramter. I'm using the load management function for the entire circuit (https://docs.evcc.io/en/docs/features/loadmanagement)

Here you can set a fixed 'maxpower' value. However this can be dynamically adjusted trough MQTT. I have it working trough MQTT now, but would be great if this parameter would be available in HA directly.

MQTT workaround:
```
circuits:
  - name: main # eindeutiger Name, wird als Referenz für andere Circuits verwendet
    title: Hoofdzekering # Anzeige in der UI (später)
    maxPower: 4500 # (optional)
    GetMaxPower:
      source: mqtt
      topic: sensor.evcc_maxpower
    meter: grid # optional
```
