### ISSUE TITLE
more services to control EVCC

### ISSUE THREAD

**Issue by dm82m** [marq24/ha-evcc#92]
### Description

hey marc,

I am currently calling two endpoints of evcc through rest calls in my home assistant instance. I found your integration and wanted to migrate to it but I saw that I can only interact with these endpoints manually in the integration ui as the integration is not providing a service on them.

Would be great if you could provide services for these calls:

```
rest_command:
  evcc_set_vehicle:
    url: "http://192.168.178.4:7070/api/loadpoints/1/vehicle/dima-car"
    method: post
  evcc_set_mode_off:
    url: "http://192.168.178.4:7070/api/loadpoints/1/mode/off"
    method: post
```

Let me know what you think.

Best,
Dirk

### API Keys

```shell

```
